version: "3.9"

services:
  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: "faheem222/kenzstore:latest"
    expose:
      - '3001'
    ports:
      - '3001:3001'


