version: "3.9"

services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    expose:
      - '3001'
    ports:
      - '3001:3001'
    volumes:
      - type: bind
        source: src
        target: /usr/src/app/src
  api-source:
    build:
      context: .
      dockerfile: Dockerfile
      target: source
  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: "faheem222/kenzstore:latest"
    expose:
      - '3001'
    ports:
      - '3001:3001'
